namespace RuneSharp.Core.GrandExchange
{
    public enum ItemCategory
    {
        Miscellaneous = 0,
        Ammo = 1,
        Arrows = 2,
        Bolts = 3,
        ConstructionMaterials = 4,
        ConstructionProjects = 5,
        CookingIngredients = 6,
        Costumes = 7,
        CraftingMaterials = 8,
        Familiars = 9,
        FarmingProduce = 10,
        FletchingMaterials = 11,
        FoodAndDrink = 12,
        HerbloreMaterials = 13,
        HuntingEquipment = 14,
        HuntingProduce = 15,
        Jewellery = 16,
        MageArmour = 17,
        MageWeapons = 18,
        MeleeArmourLowLevel = 19,
        MeleeArmourMidLevel = 20,
        MeleeArmourHighLevel = 21,
        MeleeWeaponsLowLevel = 22,
        MeleeWeaponsMidLevel = 23,
        MeleeWeaponsHighLevel = 24,
        MiningAndSmithing = 25,
        Potions = 26,
        PrayerArmour = 27,
        PrayerMaterials = 28,
        RangeArmour = 29,
        RangeWeapons = 30,
        Runecrafting = 31,
        RunesSpellsAndTeleports = 32,
        Seeds = 33,
        SummoningScrolls = 34,
        ToolsAndContainers = 35,
        WoodcuttingProduct = 36,
        PocketItems = 37,
        StoneSpirits = 38,
        Salvage = 39,
        FiremakingProducts = 40,
    }
}